name: CI
on: [push]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
      - run: npx jest --ci
